import type { CSSProperties } from "react";

export const s = {
  card: (rejected: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: 16,
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    opacity: rejected ? 0.55 : 1,
    transition: "opacity .15s",
  }),
  topRow: { display: "flex", alignItems: "flex-start", gap: 10 } satisfies CSSProperties,
  categoryBadge: {} satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 16 } satisfies CSSProperties,
  ruleWrap: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  ruleText: {
    fontSize: 15,
    fontWeight: 600,
    lineHeight: 1.5,
    cursor: "pointer",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  actionsCol: { display: "flex", flexDirection: "column", gap: 6, flexShrink: 0 } satisfies CSSProperties,
  editRow: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  editActions: { display: "flex", gap: 8, justifyContent: "flex-end" } satisfies CSSProperties,
  evidenceRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  evidenceChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "2px 8px",
    borderRadius: 5,
    fontSize: 12,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "10px 12px",
    borderRadius: 7,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    fontSize: 12.5,
    lineHeight: 1.5,
    overflowX: "auto",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  confidenceRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  confidenceLabel: {
    fontSize: 12,
    color: "var(--text-muted)",
    minWidth: 64,
  } satisfies CSSProperties,
  confidenceBarWrap: {
    width: 140,
    border: "1px solid var(--border-strong)",
    borderRadius: 99,
  } satisfies CSSProperties,
  confidenceValue: { fontSize: 12, color: "var(--text-secondary)", minWidth: 32, textAlign: "right" } satisfies CSSProperties,
} as const;
