import type { CSSProperties } from "react";

/** Co-located styles for ContextDocPicker. */
export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  search: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "7px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 240,
  } satisfies CSSProperties,
  searchIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-secondary)", margin: 0 } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", margin: 0 } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: (on: boolean, isDragging: boolean, draggable: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 8,
    border: `1px solid ${on ? "var(--border-strong)" : "var(--border)"}`,
    background: on ? "var(--bg-elevated)" : "var(--bg-surface)",
    opacity: isDragging ? 0.45 : 1,
    cursor: draggable ? "grab" : "default",
  }),
  handle: (active: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    display: "inline-flex",
    visibility: active ? "visible" : "hidden",
  }),
  checkboxWrap: { flex: 1, minWidth: 0, display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  readOnlyCheckbox: { pointerEvents: "none", opacity: 0.6 } satisfies CSSProperties,
  name: {
    fontSize: 13.5,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
  } satisfies CSSProperties,
  folder: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  note: (warn: boolean): CSSProperties => ({
    fontSize: 11,
    padding: "2px 8px",
    borderRadius: 5,
    flexShrink: 0,
    color: warn ? "var(--warn)" : "var(--text-secondary)",
    background: warn ? "var(--warn-bg)" : "var(--bg-hover)",
  }),
  typeChip: (color: string): CSSProperties => ({
    fontSize: 11,
    padding: "2px 8px",
    borderRadius: 5,
    color,
    border: `1px solid ${color}`,
    flexShrink: 0,
  }),
  previewBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    padding: "5px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-secondary)",
    cursor: "pointer",
    flexShrink: 0,
  } satisfies CSSProperties,
  footer: {
    borderTop: "1px solid var(--border)",
    paddingTop: 12,
    display: "flex",
    alignItems: "center",
    gap: 12,
  } satisfies CSSProperties,
  total: (warn: boolean): CSSProperties => ({
    fontSize: 13,
    color: warn ? "var(--warn)" : "var(--text-secondary)",
  }),
  modalBody: { padding: "16px 24px", fontSize: 14 } satisfies CSSProperties,
  modalError: { padding: "16px 24px", fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,
} as const;
